baseURL = "https://labs.cobaugh.io/"
relativeURLs = true
canonifyURLs = true
publishDir = "public"
disablePathToLower = true

languageCode = "en-us"
title = "Cobaugh Labs"
theme = "hugo-material-docs"
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-112422997-1"

enableGitInfo = true

refLinksNotFoundURL = "404.html"

SectionPagesMenu = "main"

timeout = 40000

[params]
	# General information
	description = "Cobaugh Labs"
	copyright = "Andrew Cobaugh"

	# Repository
	provider = ""
	repo_url = ""

	version = ""
	logo = "images/logo.jpg"
	favicon = "/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = [ "css/custom.css" ]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[[menu.main]]
	name   = "News"
	identifier = "news"
	url = 'news/'
	weight = 5

[[menu.main]]
	name   = "High Voltage"
	identifier = "hv"
	url    = "hv/"
	weight = 10

[[menu.main]]
	name   = "Tools"
	identifier = "tools"
	url    = "tools/"
	weight = 20

[[menu.main]]
	name   = "Restoration"
	identifier = "restoration"
	url    = "resto/"
	weight = 30

[[menu.main]]
	name   = "Motorcycles"
	identifier = "moto"
	url    = "moto/"
	weight = 35

[[menu.main]]
	name   = "Lasers"
	identifier = "lasers"
	url    = "#"
	weight = 40 

[[menu.main]]
	name   = "Amateur Radio"
	identifier = "ham"
	url    = "/ham"
	weight = 45

[[menu.main]]
	name   = "Code"
	identifier = "code"
	url    = "https://github.com/acobaugh"
	weight = 50

[[menu.main]]
	name = "About"
	identifier = "about"
	url = "https://andrew.cobaugh.io/#about"
	weight = 100

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[imaging]
	quality = 100
	resampleFilter = "CatmullRom"
	#resampleFilter = "Lanczos"
	#resampleFilter = "NearestNeighbor"
	anchor = "smart"

[imaging.exif]
	disableLatLong = true